version: '3.8'

services:
  canara_app:
    image: abhi539/spring-kannada-poets
    container_name: spring-kannada-poets
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    restart: always
